---
- hosts: all
  become: yes

  tasks:
    - name: removing package
      apt:
        name: apache2
        state: absent

    - name: Delete content & directory
      file:
        state: absent
        path: /etc/apache2/
