---
- hosts: slave
  become: yes

  tasks:
    - name: installing package
      apt:
        name: apache2
        state: present

- hosts: debain
  become: yes

  tasks:
    - name: installing package
      apt:
        name: apache2
        state: present

- hosts: jenkins
  become: yes

  tasks:
    - name: installing package
      apt:
        name: apache2
        state: present
