---
- hosts: slave
  become: yes

  tasks:
    - name: Un-installing package apache2
      apt:
        name: apache2
        state: absent

- hosts: debain
  become: yes

  tasks:
    - name: Un-installing package apache2
      apt:
        name: apache2
        state: absent

- hosts: jenkins
  become: yes

  tasks:
    - name: Un-installing package apache2
      apt:
        name: apache2
        state: absent
