---
- hosts: all
  become: yes

  tasks:
    - name: removing package
      apt:
        name: apache2
        state: absent

    - name: Going to Delete Apache2
      ansible.builtin.shell:
        cmd: rm -rf /etc/apache2/
