---
- hosts: all
  become: yes

  tasks:
    - name: installing package
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
