---
- hosts: all
  become: true
#  gather_facts: False
  tasks:
    - name: Check Dist Version
      shell: cat /etc/os-release
      register: response

    - debug: msg="{{ response.stdout }}"

    - name: installing package
      apt: name=apache2 update_cache=yes state=latest
    
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present

    - name: apache2 listen on port 8082
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8082" state=present
        
    - name: apache2 virtualhost on port 8082
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8082>" state=present
