---
- hosts: all
  tasks: Install Websever depening upon the OS

- name: Install the correct web server for RHEL
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
 
- name: Install the correct web server for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
